import type { NextPage } from "next";
import Head from "next/head";

import Bio from "components/Bio";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Alexis Osuna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Bio />
      </main>
    </div>
  );
};

export default Home;
