import Head from "next/head";
import type { NextPage } from "next";
import { compareDesc } from "date-fns";
import { allPosts } from "contentlayer/generated";
import { Post } from "contentlayer/generated";

import Container from "components/Container";
import Bio from "components/Bio";
import LatestPosts from "components/LatestPosts";
import CurrentlyPlaying from "components/CurrentlyPlaying";

export async function getStaticProps() {
  const posts = allPosts.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });
  return { props: { posts } };
}

interface Props {
  posts: Post[];
}

const Home: NextPage<Props> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Alexis Osuna</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Bio />
          <LatestPosts posts={posts} />
          <CurrentlyPlaying />
        </Container>
      </main>
    </>
  );
};

export default Home;
